### ISSUE TITLE
Bot sends message info on sending any number in ai chat

### ISSUE THREAD

**Issue by Cosmos023** [LuCk-exxtreme/Livin-in-Thug#1]
![Screenshot_2022-02-15-12-01-43-740](https://user-images.githubusercontent.com/91662390/154005743-e040ec2b-0221-483f-a898-9992ecbbacce.jpeg)

**Comment by LuCk-exxtreme** [comment]
Well I'll fix it up in a while It is some discord.js code evaluation bug

**Comment by LuCk-exxtreme** [comment]
Issue Fixed thanks for let me know
